[package]
name = "jsonboard"
version = "0.1.0"
edition.workspace = true

[dependencies]
clipboardmon.workspace = true
anyhow.workspace = true
env_logger.workspace = true
serde_json.workspace = true

[lints]
workspace = true
