[package]
name = "wl"
version = "0.1.0"
edition.workspace = true
description = "A Rust tool that shows which program is listening on a given port"

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
listeners.workspace = true

[lints]
workspace = true
