[package]
name = "inscribe"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
git2.workspace = true
indicatif.workspace = true

[lints]
workspace = true
