[package]
name = "dirhash"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap.workspace = true
sha2.workspace = true
anyhow.workspace = true
rayon.workspace = true
ignore.workspace = true

[lints]
workspace = true
