[package]
name = "repotidy"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "repotidy"
path = "src/main.rs"

[dependencies]
buildinfo.workspace = true
repowalker.workspace = true

[lints]
workspace = true
