[package]
name = "hexfind"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
hex.workspace = true
memmap2.workspace = true

[lints]
workspace = true
