[package]
name = "tubeboard"
version = "0.1.0"
edition.workspace = true

[dependencies]
clipboardmon.workspace = true
anyhow.workspace = true
env_logger.workspace = true
url.workspace = true

[lints]
workspace = true
