[package]
name = "portplz"
version = "0.1.0"
edition.workspace = true

[dependencies]
buildinfo.workspace = true
clap.workspace = true
gix.workspace = true
sha2.workspace = true

[lints]
workspace = true
