[package]
name = "clipboardmon"
version = "0.1.0"
edition.workspace = true

[dependencies]
arboard.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true

[lints]
workspace = true
