[package]
name = "rr"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "rr"
path = "src/main.rs"

[dependencies]
repowalker.workspace = true
walkdir.workspace = true
clap.workspace = true

[lints]
workspace = true
