[package]
name = "polish"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "polish"
path = "src/main.rs"

[dependencies]
walkdir.workspace = true
clap.workspace = true
repowalker.workspace = true

[lints]
workspace = true
