[package]
name = "update-aws-credentials"
version = "0.1.0"
edition.workspace = true
authors = ["Tim Mattison"]
description = "Takes AWS credentials from clipboard and updates AWS credentials file"

[dependencies]
arboard.workspace = true
aws-config.workspace = true
aws-credential-types.workspace = true
aws-sdk-sts.workspace = true
tokio.workspace = true
anyhow.workspace = true
dirs.workspace = true

[lints]
workspace = true
