[package]
name = "safeboard"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
clipboardmon.workspace = true
env_logger.workspace = true
log.workspace = true
rodio.workspace = true

[lints]
workspace = true
