[package]
name = "gr8"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "gr8"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
colored.workspace = true
anyhow.workspace = true

[lints]
workspace = true
