[package]
name = "rcc"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
serde.workspace = true
toml.workspace = true
which.workspace = true

[lints]
workspace = true
