[package]
name = "reposize"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "reposize"
path = "src/main.rs"

[dependencies]
repowalker.workspace = true
num-format.workspace = true

[lints]
workspace = true
