[package]
name = "r2-bucket-cleaner"
version = "0.1.0"
edition.workspace = true
authors = ["Tim Mattison"]
description = "A tool to list and clear all objects from a Cloudflare R2 bucket"
license = "MIT"

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
dialoguer.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
