[package]
name = "prhash"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap.workspace = true
indicatif.workspace = true
crossterm.workspace = true
anyhow.workspace = true
tokio.workspace = true
blake3.workspace = true
sha2.workspace = true
md-5.workspace = true
sha1.workspace = true
hex.workspace = true

[lints]
workspace = true
