[package]
name = "wifiqr"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
image.workspace = true
qrcode.workspace = true

[lints]
workspace = true
