[package]
name = "tc"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
tiktoken-rs.workspace = true

[lints]
workspace = true
