[package]
name = "idear"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
walkdir.workspace = true

[lints]
workspace = true
