[package]
name = "cf"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
filewalker.workspace = true

[lints]
workspace = true
