[package]
name = "wolly"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
get_if_addrs.workspace = true

[lints]
workspace = true
