[package]
name = "runat"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "runat"
path = "src/main.rs"

[dependencies]
buildinfo.workspace = true
chrono.workspace = true
clap.workspace = true
crossterm.workspace = true
ratatui.workspace = true

[lints]
workspace = true
