[package]
name = "aa"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
aws-config.workspace = true
aws-sdk-sts.workspace = true
buildinfo.workspace = true
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
