[package]
name = "freeport"
version = "0.1.0"
edition.workspace = true
description = "A Rust tool that finds a free TCP port on localhost"

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
rand.workspace = true

[lints]
workspace = true
